GPF.LawFirmPortal/Controllers/UserActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using GPF.LawFirmPortal.Application.Admin.Queries;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace GPF.LawFirmPortal.Controllers
{
    public class UserActivityController : BaseController
    {
        private readonly IMediator _mediator;
        public UserActivityController(IMediator mediator)
        {
            this._mediator = mediator;
        }
        public IActionResult Index()
        {
            ViewBag.Title = "User Activity's";
            return View();
        }
        [HttpGet]
        public async Task<object> GetUserActivity(DataSourceLoadOptions loadOptions)
        {           
            var userActivities = await Mediator.Send(new GetUserActivityQuery()).ConfigureAwait(true);
            return DataSourceLoader.Load(userActivities, loadOptions);
        }
    }
}

GPF.LawFirmPortal/Views/Shared/_BreadcrumbPartial.cshtml
@using System.Security.Claims;

@if (User.Identity.IsAuthenticated)
{
    @if (ViewBag.Breadcrumbs != null)
    {
    <div class="page-breadcrumb">
        <div class="row align-items-center">
            <div class="col-md-12 col-lg-2 align-self-center">
                <h3 class="page-title">@ViewBag.Title</h3>
                @*<div class="d-flex align-items-center">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            @foreach (var breadcrumb in ViewBag.Breadcrumbs as List<Breadcrumb>)
                            {
                                if (breadcrumb.Active)
                                {
                                    <li class="breadcrumb-item active"><a asp-action="@breadcrumb.Action" asp-controller="@breadcrumb.Controller">@breadcrumb.Text</a></li>
                                }
                                else
                                {
                                    <li class="breadcrumb-item" aria-current="page">@breadcrumb.Text</li>
                                }
                            }
                        </ol>
                    </nav>
                </div>*@
            </div>
        </div>
    </div>
        }
    }

GPF.LawFirmPortal/Views/Shared/_CaseInfoPopup.cshtml
@using GPF.LawFirmPortal.Application.CaseUpdate.ViewModel

@(Html.DevExtreme().Form<CaseDueUpdatesViewModel>()
        .ID("caseInfoPopup")
        .ColCountByScreen(c => c.Xs(1).Lg(1).Md(1).Sm(1))
        .MinColWidth(250)
        .ScrollingEnabled(true)
        .ColCount(Mode.Auto)
        .LabelLocation(FormLabelLocation.Top)
        .AlignItemLabels(true)
        .ScreenByWidth("dashboard.CaseInfoScreenByWidth")
        .Items(items => {
            items.AddGroup()
                    .ColCount(2)
                    .ColSpan(2)
                    .Items(groupItems =>
                    {
                        groupItems.AddSimpleFor(m => m.CombinedName).VisibleIndex(1).Label(l => l.Text("Client Name")).Editor(e => e.SelectBox().ID("CombinedNameSelectBox").DataSource(d => d.Mvc().Controller("Home").LoadAction("GetClientNames").Key("PortfolioId"))
                        .OnItemClick("dashboard.ClientValueChanged").SearchEnabled(true).ValueExpr("PortfolioId").DisplayExpr("CombinedName").Placeholder("Type client name..."));
                        groupItems.AddSimpleFor(m => m.AmountOwed).VisibleIndex(2).Label(l => l.Text("Amount Owed")).Editor(e => e.NumberBox().Format("$ #,##0.##").Disabled(true));
                        groupItems.AddSimpleFor(m => m.DOB).VisibleIndex(3).Editor(e => e.DateBox().Disabled(true));
                        groupItems.AddSimpleFor(m => m.DOL).VisibleIndex(4).Label(l => l.Text("Date of Loss")).Editor(e => e.DateBox().Disabled(true));
                        groupItems.AddSimpleFor(m => m.CasePhaseID).VisibleIndex(5).Editor(e => e.SelectBox().ID("ddlCasePhasePopup").OnValueChanged("dashboard.OnCasePhaseChangePopup").DataSource(d => d.Mvc().Controller("Home").LoadAction("GetCasePhase").Key("LfcasePhaseId"))
                            .DisplayExpr("LfcasePhaseName").ValueExpr("LfcasePhaseId")).IsRequired(true).Label(l => l.Text("Case Phase"));
                        groupItems.AddSimpleFor(m => m.CaseStatusReasonID).VisibleIndex(6).Editor(e => e.SelectBox().Disabled(true).OnItemClick("dashboard.OnCaseStatusClickPopup").OnContentReady("dashboard.CaseStatusContentReadyPopup").ID("ddlCaseStatusReasonPopup").DataSource(d => d.Mvc().Controller("Home").LoadAction("GetReasons").Key("Id"))
                            .DisplayExpr("LfcaseDetailsName").ValueExpr("Id")).IsRequired(true).Label(l => l.Text("Status Detail"));
                        groupItems.AddSimpleFor(m => m.TrialDateAssigned).VisibleIndex(7).Editor(e => e.DateBox()).Visible(false);
                        groupItems.AddSimpleFor(m => m.DepositionsStatus).VisibleIndex(8).Editor(e => e.SelectBox().DataSource(Html.GetEnumSelectList<DepositionsStatus>().Select(i => new { Value = int.Parse(i.Value), Text = i.Text })).ValueExpr("Value").DisplayExpr("Text")).Visible(false);
                        groupItems.AddEmpty().Name("EmptySpace").Visible(false).VisibleIndex(9);
                        groupItems.AddSimpleFor(m => m.Note).VisibleIndex(10).ColSpan(2).Editor(editor => editor.TextArea().Height(70));
                        groupItems.AddSimpleFor(m => m.PortfolioId).Visible(false);
                        groupItems.AddSimpleFor(m => m.CaseId).Visible(false);
                    });
        })
    )

GPF.LawFirmPortal/Views/Shared/_HeaderPartial.cshtml
@using System.Security.Claims;
@inject Microsoft.Extensions.Options.IOptions<GPF.LawFirmPortal.Application.Common.Utility.Appsettings> metaOptions

    @if (User.Identity.IsAuthenticated)
{
    var userEmail = ((ClaimsIdentity)User.Identity).FindFirst("Email");
    var displayName = ((ClaimsIdentity)User.Identity).FindFirst("DisplayName");
    var LawFirmName = ((ClaimsIdentity)User.Identity).FindFirst("LawFirmName");
    var LawFirmSName = ((ClaimsIdentity)User.Identity).FindFirst("LawFirmSName");
    var options = metaOptions.Value;
    var userGroup = ((ClaimsIdentity)User.Identity).FindFirst("UserGroup");
    <header class="topbar" data-navbarbg="skin6">
        <nav class="navbar top-navbar navbar-expand-md navbar-dark">
            <div class="navbar-header" data-logobg="skin6">
                <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                <!-- ============================================================== -->
                <!-- Logo -->
                <!-- ============================================================== -->
                <a class="navbar-brand" asp-action="Dashboard" asp-controller="Home">
                    <!-- Logo icon -->
                    <img src="/images/gpf-pear1.png" alt="Home" style="width: 37px;height: 30px;">
                        <span class="topbar-title">Law Firm Portal</span>
                    <!--End Logo icon -->
                    <!-- Logo text -->
                    <span class="logo-text">
                        @*<h2 class="dark-logo" style="display:block;font-size: smaller;white-space: pre-wrap;">@LawFirmName.Value</h2>*@
                        <!-- dark Logo text -->
                        <img src="~/layout/assets/images/logo-text.png" alt="homepage" class="dark-logo" style="display:none;"/>

                    </span>
                </a>

                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- toggle and nav items -->
                <!-- ============================================================== -->
                <a class="nav-toggler waves-effect waves-light text-dark d-block d-md-none"
                   href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
            </div>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="fas fa-bars"></i></a></li>
                    @if (userGroup.Value == options.LdapSettings.AdminRole)
                    { 
                        <li class="nav-item dropdown">
                            <a id="notification" class="nav-link dropdown-toggle waves-effect waves-dark" href="javascript:void(0)" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="mdi mdi-message"></i>
                                <div class="notify" style="display:none;"> <span class="heartbit"></span> <span class="point"></span> </div>
                            </a>
                            <div class="dropdown-menu mailbox animated bounceInDown">
                                <ul class="list-style-none">
                                    <li>
                                        <div class="font-weight-medium border-bottom rounded-top py-3 px-4">
                                            Notifications
                                        </div>
                                    </li>
                                    <li>
                                        <div class="message-center notifications position-relative ps-container ps-theme-default" style="height:250px;" id="messagenotification">
                                            <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div>
                                        </div>
                                    </li>
                                    <li>
                                        <a class="nav-link border-top text-center text-dark pt-3" onclick="MarkAllRead();" href="javascript:void(0);"> <strong>Mark all read</strong> <i class="fa fa-angle-right"></i> </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    }
                </ul>
                <!-- ============================================================== -->
                <!-- toggle and nav items -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Right side toggle and nav items -->
                <!-- ============================================================== -->
                <ul class="navbar-nav">
                    <!-- ============================================================== -->
                    <!-- User profile and search -->
                    <!-- ============================================================== -->
                    <li class="nav-item hidden-sm-down">
                        <form class="app-search mt-3 mr-2">
                            @*<input type="text" class="form-control rounded-pill border-0" placeholder="Search for...">
                                <a class="srh-btn"><i class="ti-search"></i></a>*@
                        </form>
                    </li>
                    <li class="nav-item dropdown" id="toastMessage">
                        <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="~/layout/assets/images/users/1.jpg" alt="user" class="rounded-circle" width="50"></a>
                        <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
                            <div class="d-flex no-block align-items-center mb-2 border-bottom">
                                <div class=""><img src="~/layout/assets/images/users/1.jpg" alt="user" class="rounded" width="80"></div>
                                <div class="ml-2">
                                    <h4 class="mb-0">@displayName.Value</h4>
                                    <p class=" mb-0">@userEmail.Value</p>
                                </div>
                            </div>
                            @if (userGroup.Value == options.LdapSettings.AdminRole)
                            {
                            <a class="dropdown-item" asp-action="Index" asp-controller="UserActivity">User Activity</a>
                            <div class="dropdown-divider"></div>
                            }
                            @using (Html.BeginForm("Logout", "Account", new { area = "" }, FormMethod.Post, true, new { id = "logoutForm", role = "form" }))
                            {
                            @*<button id="logout" type="submit" class="dropdown-item nav-link-drpdwn text-left"> <i class="fa fa-power-off mr-1 ml-1"></i>Logout</button>*@
                            <a class="dropdown-item" href="javascript:void(0);" onclick="javascript:document.getElementById('logoutForm').submit()">Logout</a>
                            }
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="row">
            <div class="col-sm-12">
                <h3>@DateTime.Now.ToString("MMMM yyyy")</h3>
            </div>
            <div class="col-sm-12">
                @if (userGroup.Value == options.LdapSettings.AdminRole)
                {
                <h1>Administrator</h1>
                }
                else
                {
                    <h1>@LawFirmName.Value</h1>
                    }
            </div>
            <div class="w-100"></div>
        </div>
            
    </header>
}
else
{
    <header class="topbar" data-navbarbg="skin6">
        <a class="navbar-brand" asp-action="Dashboard" asp-controller="Home">
            <img src="/images/gpf-pear1.png" alt="Home" style="width: 37px;height: 30px;">
            <span class="topbar-title">Law Firm Portal</span>
        </a>
    </header>
}

GPF.LawFirmPortal/Views/Shared/_Layout.cshtml
@using GPF.LawFirmPortal.Application.Common.Utility
@inject Microsoft.Extensions.Options.IOptions<GPF.LawFirmPortal.Application.Common.Utility.Appsettings> metaOptions
@{
    var toastrErrorMsg = String.Empty;
    var toastrSuccessMsg = String.Empty;


    if (TempData[AppConstants.GPFSettings.ERRORMSG] != null)
    {
        toastrErrorMsg = TempData[AppConstants.GPFSettings.ERRORMSG].ToString();
    }
    if (TempData[AppConstants.GPFSettings.SUCCESSMSG] != null)
    {
        toastrSuccessMsg = TempData[AppConstants.GPFSettings.SUCCESSMSG].ToString();
    }
    var options = metaOptions.Value;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex,nofollow">
    <title>@ViewData["Title"] - LawFirm Portal</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/layout/assets/images/favicon.png" />

    <link href="~/css/devextreme/dx.common.css" rel="stylesheet" />
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />
    <!-- Custom CSS
    <link href="~/layout/assets/plugins/chartist/dist/chartist.min.css" rel="stylesheet"> -->
    <!-- Custom CSS -->
    <link href="~/layout/css/style.min.css" rel="stylesheet">
    <link href="~/css/lfp.css" rel="stylesheet">
    <script src="~/layout/js/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    @*<script src="~/layout/js/popper.min.js"></script>*@
    <script src="~/layout/js/bootstrap.min.js"></script>
    <!-- apps -->
    <script src="~/layout/js/app.min.js" asp-append-version="true"></script>
    <script src="~/layout/js/app.init.js" asp-append-version="true"></script>
    <!-- Theme settings -->
    @*<script src="~/layout/js/app-style-switcher.js"></script>*@
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="~/layout/js/perfect-scrollbar.jquery.min.js"></script>
    @*<script src="~/layout/js/jquery.sparkline.min.js"></script>*@
    <!--Menu sidebar -->
    @*<script src="~/layout/js/sidebarmenu.js"></script>*@
    <!--Custom JavaScript -->
    @*<script src="~/layout/js/feather.min.js"></script>*@
    <script src="~/layout/js/custom.js"></script>
    <!--This page JavaScript -->
    <script src="~/js/devextreme/jszip.js"></script>

    <script src="~/js/devextreme/dx.all.js"></script>

    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
    <script src="~/lib/application-js/common.js" asp-append-version="true"></script>
    <script src="~/layout/js/waves.js" asp-append-version="true"></script>
    <script src="~/layout/js/jquery.blockUI.js" asp-append-version="true"></script>
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/ConnectSignalR.js" asp-append-version="true"></script>

    <script type="text/javascript">
        var isSubscribed = null;
    </script>
    <style type="text/css">
        .jqstooltip {
            position: absolute;
            left: 0px;
            top: 0px;
            visibility: hidden;
            background: rgb(0, 0, 0) transparent;
            background-color: rgba(0,0,0,0.6);
            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000);
            -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000)";
            color: white;
            font: 10px arial, san serif;
            text-align: left;
            white-space: nowrap;
            padding: 5px;
            border: 1px solid white;
            box-sizing: content-box;
            z-index: 10000;
        }

        .jqsfield {
            color: white;
            font: 10px arial, san serif;
            text-align: left;
        }
    </style>
</head>
<body class="pb-0">
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- =================================data-sidebartype="full"============================= -->
    <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="mini-sidebar" data-boxed-layout="full">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <partial name="_HeaderPartial" />
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <partial name="_MenuPartial" />
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="@(User.Identity.IsAuthenticated == true ? "page-wrapper" : "none")">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <partial name="_BreadcrumbPartial" />
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->

            @RenderBody()
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <footer class="footer">
                <div class="container-fluid">
                    <div class="row text-center">
                        <div class="col-lg-4" style="text-align:left;">© @DateTime.Now.Year, All rights reserved by Golden Pear Funding</div>
                        <div class="col-lg-4">@options.AppVersion</div>
                    </div>
                </div>
            </footer>
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    @{
        if (User.Identity.IsAuthenticated == true)
        {
            <partial name="_PwaInit.cshtml" />
        }
    }


    @RenderSection("Scripts", required: false)
</body>
</html>
<style>
    .UnSubscribenotification {
        display: none;
    }

    .intercom-lightweight-app-launcher {
        position: fixed;
        z-index: 2147483003;
        bottom: 20px;
        right: 20px;
        width: 60px;
        height: 60px;
        border-radius: 50%;
        background: #094547;
        cursor: pointer;
        box-shadow: 0 1px 6px 0 rgb(0 0 0 / 6%), 0 2px 32px 0 rgb(0 0 0 / 16%);
        animation: intercom-lightweight-app-launcher 250ms ease;
    }

    .intercom-lightweight-app-launcher-icon-open {
        opacity: 1;
        transform: rotate( 0deg ) scale(1);
    }

        .intercom-lightweight-app-launcher-icon-open svg {
            width: 28px;
            height: 32px;
        }

            .intercom-lightweight-app-launcher-icon-open svg path {
                fill: rgb(255, 255, 255);
            }

    .intercom-lightweight-app-launcher-icon {
        display: flex;
        align-items: center;
        justify-content: center;
        position: absolute;
        top: 0;
        left: 0;
        width: 60px;
        height: 60px;
        transition: transform 100ms linear, opacity 80ms linear;
    }
</style>

GPF.LawFirmPortal/Views/Shared/_MenuPartial.cshtml
@using System.Security.Claims;
@inject Microsoft.Extensions.Options.IOptions<GPF.LawFirmPortal.Application.Common.Utility.Appsettings> metaOptions

@if (User.Identity.IsAuthenticated)
{
    var options = metaOptions.Value;
    var userGroup = ((ClaimsIdentity)User.Identity).FindFirst("UserGroup");
    var LawFirmName = ((ClaimsIdentity)User.Identity).FindFirst("LawFirmName");
    <aside class="left-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
            <!-- Sidebar navigation-->
            @*<nav class="sidebar-nav">
                <ul id="sidebarnav" class="in">
        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" asp-action="Dashboard" asp-controller="Home" aria-expanded="false"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-circle feather-icon"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg><span class="hide-menu">Dashboard</span></a></li>
        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" asp-action="Index" asp-controller="DueCaseUpdate" aria-expanded="false"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layout feather-icon"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg><span class="hide-menu">Case Due for Updates</span></a></li>
        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" asp-action="OpenCases" asp-controller="DueCaseUpdate" aria-expanded="false"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-sidebar feather-icon"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="9" y1="3" x2="9" y2="21"></line></svg><span class="hide-menu">Open Case</span></a></li>
        <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="Home/Privacy" aria-expanded="false"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar feather-icon"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg><span class="hide-menu">Privacy</span></a></li>
        @if (userGroup.Value == options.LdapSettings.AdminRole)
        {
            <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" asp-action="Index" asp-controller="UserActivity" aria-expanded="false"><svg xmlns="http://www.w3.org/2000/svg" fill="none" height="24" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12" /></svg><span class="hide-menu">User Activity</span></a></li>
            <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="app-todo.html" aria-expanded="false"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-circle feather-icon"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg><span class="hide-menu">Todo</span></a></li>
        }
        </ul>
        </nav>*@
            <!-- End Sidebar navigation -->
        </div>
            <!-- End Sidebar scroll-->
</aside>
}